### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by PaulRBerg** [shrpne/from-exponential#1]
Love this package, it solves the problems that plague the script shared in this [GitHub gist](https://gist.github.com/jiggzson/b5f489af9ad931e3d186). Yet, I can't use this with TypeScript, since there are no exported types, and there is no `@types/from-exponential` that I can install.

**Comment by shrpne** [comment]
Thanks for the feedback. Unfortunately, I have little experience with typescript. Help with it will be welcome.
